src/Entity/Medicament.php
<?php

namespace App\Entity;

use App\Repository\MedicamentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: MedicamentRepository::class)]
class Medicament
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"libelle required")]
    private ?string $libelle = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"fabricant required")]
    private ?string $fabricant = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"durée de conservation required")]
    private ?string $duree_conservation = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"forme required")]
    private ?string $forme = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"gamme required")]
    private ?string $gamme = null;

    #[ORM\ManyToMany(targetEntity: Ordonnance::class, mappedBy: 'ord')]
    private Collection $medic;

    public function __construct()
    {
        $this->medic = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getFabricant(): ?string
    {
        return $this->fabricant;
    }

    public function setFabricant(string $fabricant): self
    {
        $this->fabricant = $fabricant;

        return $this;
    }

    public function getDureeConservation(): ?string
    {
        return $this->duree_conservation;
    }

    public function setDureeConservation(string $duree_conservation): self
    {
        $this->duree_conservation = $duree_conservation;

        return $this;
    }

    public function getForme(): ?string
    {
        return $this->forme;
    }

    public function setForme(string $forme): self
    {
        $this->forme = $forme;

        return $this;
    }

    public function getGamme(): ?string
    {
        return $this->gamme;
    }

    public function setGamme(string $gamme): self
    {
        $this->gamme = $gamme;

        return $this;
    }

    /**
     * @return Collection<int, Ordonnance>
     */
    public function getMedic(): Collection
    {
        return $this->medic;
    }

    public function addMedic(Ordonnance $medic): self
    {
        if (!$this->medic->contains($medic)) {
            $this->medic->add($medic);
            $medic->addOrd($this);
        }

        return $this;
    }

    public function removeMedic(Ordonnance $medic): self
    {
        if ($this->medic->removeElement($medic)) {
            $medic->removeOrd($this);
        }

        return $this;
    }
    public function __toString()
    {
        return $this->id;
    }

}

src/Form/MedicamentType.php
<?php

namespace App\Form;

use App\Entity\Medicament;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MedicamentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('libelle')
            ->add('fabricant')
            ->add('duree_conservation')
            ->add('forme')
            ->add('gamme')
            ->add('medic')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Medicament::class,
        ]);
    }
}

src/Controller/MedicamentController.php
<?php

namespace App\Controller;

use App\Entity\Medicament;
use App\Form\MedicamentType;
use App\Repository\MedicamentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/medicament')]
class MedicamentController extends AbstractController
{
    #[Route('/', name: 'app_medicament_index', methods: ['GET'])]
    public function index(MedicamentRepository $medicamentRepository): Response
    {
        return $this->render('medicament/index.html.twig', [
            'medicaments' => $medicamentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_medicament_new', methods: ['GET', 'POST'])]
    public function new(Request $request, MedicamentRepository $medicamentRepository): Response
    {
        $medicament = new Medicament();
        $form = $this->createForm(MedicamentType::class, $medicament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $medicamentRepository->save($medicament, true);

            return $this->redirectToRoute('app_medicament_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('medicament/new.html.twig', [
            'medicament' => $medicament,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_medicament_show', methods: ['GET'])]
    public function show(Medicament $medicament): Response
    {
        return $this->render('medicament/show.html.twig', [
            'medicament' => $medicament,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_medicament_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Medicament $medicament, MedicamentRepository $medicamentRepository): Response
    {
        $form = $this->createForm(MedicamentType::class, $medicament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $medicamentRepository->save($medicament, true);

            return $this->redirectToRoute('app_medicament_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('medicament/edit.html.twig', [
            'medicament' => $medicament,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_medicament_delete', methods: ['POST'])]
    public function delete(Request $request, Medicament $medicament, MedicamentRepository $medicamentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$medicament->getId(), $request->request->get('_token'))) {
            $medicamentRepository->remove($medicament, true);
        }

        return $this->redirectToRoute('app_medicament_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/medicament/_delete_form.html.twig
<form method="post" action="{{ path('app_medicament_delete', {'id': medicament.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ medicament.id) }}">
    <button class="btn">Delete</button>
</form>

templates/medicament/_form.html.twig
{{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
<table>
    <tr>
        <td>{{ form_label(form.libelle,"libelle") }}</td>
        <td>{{ form_widget(form.libelle) }}</td>
        <td>{{ form_errors(form.libelle) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.fabricant,"fabricant") }}</td>
        <td>{{ form_widget(form.fabricant) }}</td>
        <td>{{ form_errors(form.fabricant) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.duree_conservation,"durée de conservation") }}</td>
        <td>{{ form_widget(form.duree_conservation) }}</td>
        <td>{{ form_errors(form.duree_conservation) }}</td>
    </tr>

    <tr>
        <td>{{ form_label(form.forme,"forme") }}</td>
        <td>{{ form_widget(form.forme) }}</td>
        <td>{{ form_errors(form.forme) }}</td>
    </tr>

    <tr>
        <td>{{ form_label(form.gamme,"gamme") }}</td>
        <td>{{ form_widget(form.gamme) }}</td>
        <td>{{ form_errors(form.gamme) }}</td>
    </tr>

</table>
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/medicament/edit.html.twig
{% extends "baseback.html.twig" %}

{% block title %}Edit Medicament{% endblock %}

{% block content %}
    <h1>Edit Medicament</h1>

    {{ include('medicament/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_medicament_index') }}">back to list</a>

    {{ include('medicament/_delete_form.html.twig') }}
{% endblock %}

templates/medicament/index.html.twig
{% extends "baseback.html.twig" %}

{% block title %}Medicament index{% endblock %}

{% block content %}
    <h1>Medicament index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Libelle</th>
                <th>Fabricant</th>
                <th>Duree_conservation</th>
                <th>Forme</th>
                <th>Gamme</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for medicament in medicaments %}
            <tr>
                <td>{{ medicament.id }}</td>
                <td>{{ medicament.libelle }}</td>
                <td>{{ medicament.fabricant }}</td>
                <td>{{ medicament.dureeConservation }}</td>
                <td>{{ medicament.forme }}</td>
                <td>{{ medicament.gamme }}</td>
                <td>
                    <a href="{{ path('app_medicament_show', {'id': medicament.id}) }}">show</a>
                    <a href="{{ path('app_medicament_edit', {'id': medicament.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_medicament_new') }}">Create new</a>
{% endblock %}

templates/medicament/new.html.twig
{% extends "base.html.twig" %}

{% block title %}New Medicament{% endblock %}

{% block content %}
    <h1>Create new Medicament</h1>

    {{ include('medicament/_form.html.twig') }}

    <a href="{{ path('app_medicament_index') }}">back to list</a>
{% endblock %}

templates/medicament/show.html.twig
{% extends "baseback.html.twig" %}

{% block title %}Medicament{% endblock %}

{% block content %}
    <h1>Medicament</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ medicament.id }}</td>
            </tr>
            <tr>
                <th>Libelle</th>
                <td>{{ medicament.libelle }}</td>
            </tr>
            <tr>
                <th>Fabricant</th>
                <td>{{ medicament.fabricant }}</td>
            </tr>
            <tr>
                <th>Duree_conservation</th>
                <td>{{ medicament.dureeConservation }}</td>
            </tr>
            <tr>
                <th>Forme</th>
                <td>{{ medicament.forme }}</td>
            </tr>
            <tr>
                <th>Gamme</th>
                <td>{{ medicament.gamme }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_medicament_index') }}">back to list</a>

    <a href="{{ path('app_medicament_edit', {'id': medicament.id}) }}">edit</a>

    {{ include('medicament/_delete_form.html.twig') }}
{% endblock %}