src/Entity/Consultation.php
<?php

namespace App\Entity;

use App\Repository\ConsultationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ConsultationRepository::class)]
class Consultation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"link required")]
    private ?string $lien_visio = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"price required")]
    private ?int $prix = null;

    #[ORM\Column(length: 255)]
    private ?string $lien_enregistrement = null;

    #[ORM\OneToOne(inversedBy: 'do', cascade: ['persist', 'remove'])]
    private ?Rdv $consul = null;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLienVisio(): ?string
    {
        return $this->lien_visio;
    }

    public function setLienVisio(string $lien_visio): self
    {
        $this->lien_visio = $lien_visio;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getLienEnregistrement(): ?string
    {
        return $this->lien_enregistrement;
    }

    public function setLienEnregistrement(string $lien_enregistrement): self
    {
        $this->lien_enregistrement = $lien_enregistrement;

        return $this;
    }

    public function getConsul(): ?Rdv
    {
        return $this->consul;
    }

    public function setConsul(?Rdv $consul): self
    {
        $this->consul = $consul;

        return $this;
    }

}

src/Form/ConsultationType.php
<?php

namespace App\Form;

use App\Entity\Consultation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConsultationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('lien_visio')
            ->add('prix')
            ->add('lien_enregistrement')
            ->add('consul')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Consultation::class,
        ]);
    }
}

src/Controller/ConsultationController.php
<?php

namespace App\Controller;

use App\Entity\Consultation;
use App\Form\ConsultationType;
use App\Repository\ConsultationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/consultation')]
class ConsultationController extends AbstractController
{
    #[Route('/', name: 'app_consultation_index', methods: ['GET'])]
    public function index(ConsultationRepository $consultationRepository): Response
    {
        return $this->render('consultation/index.html.twig', [
            'consultations' => $consultationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_consultation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ConsultationRepository $consultationRepository): Response
    {
        $consultation = new Consultation();
        $form = $this->createForm(ConsultationType::class, $consultation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $consultationRepository->save($consultation, true);

            return $this->redirectToRoute('app_consultation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('consultation/new.html.twig', [
            'consultation' => $consultation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_consultation_show', methods: ['GET'])]
    public function show(Consultation $consultation): Response
    {
        return $this->render('consultation/show.html.twig', [
            'consultation' => $consultation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_consultation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Consultation $consultation, ConsultationRepository $consultationRepository): Response
    {
        $form = $this->createForm(ConsultationType::class, $consultation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $consultationRepository->save($consultation, true);

            return $this->redirectToRoute('app_consultation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('consultation/edit.html.twig', [
            'consultation' => $consultation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_consultation_delete', methods: ['POST'])]
    public function delete(Request $request, Consultation $consultation, ConsultationRepository $consultationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$consultation->getId(), $request->request->get('_token'))) {
            $consultationRepository->remove($consultation, true);
        }

        return $this->redirectToRoute('app_consultation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/consultation/_delete_form.html.twig
<form method="post" action="{{ path('app_consultation_delete', {'id': consultation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ consultation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/consultation/_form.html.twig
{{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
<table>
    <tr>
        <td>{{ form_label(form.lien_visio,"lien_visio") }}</td>
        <td>{{ form_widget(form.lien_visio) }}</td>
        <td>{{ form_errors(form.lien_visio) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.prix,"prix") }}</td>
        <td>{{ form_widget(form.prix) }}</td>
        <td>{{ form_errors(form.prix) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.lien_enregistrement,"lien_enregistrement") }}</td>
        <td>{{ form_widget(form.lien_enregistrement) }}</td>
        <td>{{ form_errors(form.lien_enregistrement) }}</td>
    </tr>

</table>
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/consultation/edit.html.twig
{% extends "baseback.html.twig" %}

{% block title %}Edit Consultation{% endblock %}

{% block content %}
    <h1>Edit Consultation</h1>

    {{ include('consultation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_consultation_index') }}">back to list</a>

    {{ include('consultation/_delete_form.html.twig') }}
{% endblock %}

templates/consultation/index.html.twig
{% extends "baseback.html.twig" %}

{% block title %}Consultation index{% endblock %}

{% block content %}

    <h1>Consultation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Lien_visio</th>
                <th>Prix</th>
                <th>Lien_enregistrement</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for consultation in consultations %}
            <tr>
                <td>{{ consultation.id }}</td>
                <td>{{ consultation.lienVisio }}</td>
                <td>{{ consultation.prix }}</td>
                <td>{{ consultation.lienEnregistrement }}</td>
                <td>
                    <a href="{{ path('app_consultation_show', {'id': consultation.id}) }}">show</a>
                    <a href="{{ path('app_consultation_edit', {'id': consultation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_consultation_new') }}" style="color:blue">Create new</a>

{% endblock %}

templates/consultation/new.html.twig
{% extends "base.html.twig" %}

{% block title %}New Consultation{% endblock %}

{% block content %}
    <h1>Create new Consultation</h1>

    {{ include('consultation/_form.html.twig') }}

    <a href="{{ path('app_consultation_index') }}">back to list</a>
{% endblock %}

templates/consultation/show.html.twig
{% extends "baseback.html.twig" %}

{% block title %}Consultation{% endblock %}

{% block content %}
    <h1>Consultation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ consultation.id }}</td>
            </tr>
            <tr>
                <th>Lien_visio</th>
                <td>{{ consultation.lienVisio }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ consultation.prix }}</td>
            </tr>
            <tr>
                <th>Lien_enregistrement</th>
                <td>{{ consultation.lienEnregistrement }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_consultation_index') }}">back to list</a>

    <a href="{{ path('app_consultation_edit', {'id': consultation.id}) }}">edit</a>

    {{ include('consultation/_delete_form.html.twig') }}
{% endblock %}