src/Entity/Ordonnance.php
<?php

namespace App\Entity;

use App\Repository\OrdonnanceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: OrdonnanceRepository::class)]
class Ordonnance
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank(message:"date required")]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"nombre de paquets required")]
    private ?int $nb_paquet = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"dosage required")]
    private ?int $dosage = null;

    #[ORM\Column(length: 255)]
    private ?string $remarque = null;

    #[ORM\ManyToMany(targetEntity: Medicament::class, inversedBy: 'medic')]
    private Collection $ord;

    #[ORM\ManyToOne(inversedBy: 'user_ord')]
    private ?User $ord_user = null;

    public function __construct()
    {
        $this->ord = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getNbPaquet(): ?int
    {
        return $this->nb_paquet;
    }

    public function setNbPaquet(int $nb_paquet): self
    {
        $this->nb_paquet = $nb_paquet;

        return $this;
    }

    public function getDosage(): ?int
    {
        return $this->dosage;
    }

    public function setDosage(int $dosage): self
    {
        $this->dosage = $dosage;

        return $this;
    }

    public function getRemarque(): ?string
    {
        return $this->remarque;
    }

    public function setRemarque(string $remarque): self
    {
        $this->remarque = $remarque;

        return $this;
    }

    /**
     * @return Collection<int, Medicament>
     */
    public function getOrd(): Collection
    {
        return $this->ord;
    }

    public function addOrd(Medicament $ord): self
    {
        if (!$this->ord->contains($ord)) {
            $this->ord->add($ord);
        }

        return $this;
    }

    public function removeOrd(Medicament $ord): self
    {
        $this->ord->removeElement($ord);

        return $this;
    }

    public function getOrdUser(): ?User
    {
        return $this->ord_user;
    }

    public function setOrdUser(?User $ord_user): self
    {
        $this->ord_user = $ord_user;

        return $this;
    }
    public function __toString()
    {
        return $this->id;
    }

}

src/Form/OrdonnanceType.php
<?php

namespace App\Form;

use App\Entity\Ordonnance;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrdonnanceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date')
            ->add('nb_paquet')
            ->add('dosage')
            ->add('remarque')
            ->add('ord')
            ->add('ord_user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ordonnance::class,
        ]);
    }
    
}

src/Controller/OrdonnanceController.php
<?php

namespace App\Controller;

use App\Entity\Ordonnance;
use App\Form\OrdonnanceType;
use App\Repository\OrdonnanceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/ordonnance')]
class OrdonnanceController extends AbstractController
{
    #[Route('/', name: 'app_ordonnance_index', methods: ['GET'])]
    public function index(OrdonnanceRepository $ordonnanceRepository): Response
    {
        return $this->render('ordonnance/index.html.twig', [
            'ordonnances' => $ordonnanceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_ordonnance_new', methods: ['GET', 'POST'])]
    public function new(Request $request, OrdonnanceRepository $ordonnanceRepository): Response
    {
        $ordonnance = new Ordonnance();
        $form = $this->createForm(OrdonnanceType::class, $ordonnance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ordonnanceRepository->save($ordonnance, true);

            return $this->redirectToRoute('app_ordonnance_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ordonnance/new.html.twig', [
            'ordonnance' => $ordonnance,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_ordonnance_show', methods: ['GET'])]
    public function show(Ordonnance $ordonnance): Response
    {
        return $this->render('ordonnance/show.html.twig', [
            'ordonnance' => $ordonnance,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_ordonnance_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Ordonnance $ordonnance, OrdonnanceRepository $ordonnanceRepository): Response
    {
        $form = $this->createForm(OrdonnanceType::class, $ordonnance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ordonnanceRepository->save($ordonnance, true);

            return $this->redirectToRoute('app_ordonnance_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ordonnance/edit.html.twig', [
            'ordonnance' => $ordonnance,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_ordonnance_delete', methods: ['POST'])]
    public function delete(Request $request, Ordonnance $ordonnance, OrdonnanceRepository $ordonnanceRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ordonnance->getId(), $request->request->get('_token'))) {
            $ordonnanceRepository->remove($ordonnance, true);
        }

        return $this->redirectToRoute('app_ordonnance_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/ordonnance/_delete_form.html.twig
<form method="post" action="{{ path('app_ordonnance_delete', {'id': ordonnance.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ordonnance.id) }}">
    <button class="btn">Delete</button>
</form>

templates/ordonnance/_form.html.twig
{{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
<table>
    <tr>
        <td>{{ form_label(form.date,"Date") }}</td>
        <td>{{ form_widget(form.date) }}</td>
        <td>{{ form_errors(form.date) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.nb_paquet,"Nombre de paquets") }}</td>
        <td>{{ form_widget(form.nb_paquet) }}</td>
        <td>{{ form_errors(form.nb_paquet) }}</td>
    </tr>
    <tr>
        <td>{{ form_label(form.dosage,"Dosage") }}</td>
        <td>{{ form_widget(form.dosage) }}</td>
        <td>{{ form_errors(form.dosage) }}</td>
    </tr>

    <tr>
        <td>{{ form_label(form.remarque,"Instructions") }}</td>
        <td>{{ form_widget(form.remarque) }}</td>
        <td>{{ form_errors(form.remarque) }}</td>
    </tr>

</table>
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/ordonnance/edit.html.twig
{% extends "baseback.html.twig" %}

{% block title %}Edit Ordonnance{% endblock %}

{% block content %}
    <h1>Edit Ordonnance</h1>

    {{ include('ordonnance/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_ordonnance_index') }}">back to list</a>

    {{ include('ordonnance/_delete_form.html.twig') }}
{% endblock %}

templates/ordonnance/index.html.twig
{% extends "baseback.html.twig" %}

{% block title %}Ordonnance index{% endblock %}

{% block content %}
    <h1>Ordonnance index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Nb_paquet</th>
                <th>Dosage</th>
                <th>Remarque</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ordonnance in ordonnances %}
            <tr>
                <td>{{ ordonnance.id }}</td>
                <td>{{ ordonnance.date ? ordonnance.date|date('Y-m-d') : '' }}</td>
                <td>{{ ordonnance.nbPaquet }}</td>
                <td>{{ ordonnance.dosage }}</td>
                <td>{{ ordonnance.remarque }}</td>
                <td>
                    <a href="{{ path('app_ordonnance_show', {'id': ordonnance.id}) }}">show</a>
                    <a href="{{ path('app_ordonnance_edit', {'id': ordonnance.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_ordonnance_new') }}">Create new</a>
{% endblock %}

templates/ordonnance/new.html.twig
{% extends "base.html.twig" %}

{% block title %}New Ordonnance{% endblock %}

{% block content %}
    <h1>Create new Ordonnance</h1>

    {{ include('ordonnance/_form.html.twig') }}

    <a href="{{ path('app_ordonnance_index') }}">back to list</a>
{% endblock %}

templates/ordonnance/show.html.twig
{% extends "baseback.html.twig" %}

{% block title %}Ordonnance{% endblock %}

{% block content %}
    <h1>Ordonnance</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ordonnance.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ ordonnance.date ? ordonnance.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nb_paquet</th>
                <td>{{ ordonnance.nbPaquet }}</td>
            </tr>
            <tr>
                <th>Dosage</th>
                <td>{{ ordonnance.dosage }}</td>
            </tr>
            <tr>
                <th>Remarque</th>
                <td>{{ ordonnance.remarque }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_ordonnance_index') }}">back to list</a>

    <a href="{{ path('app_ordonnance_edit', {'id': ordonnance.id}) }}">edit</a>

    {{ include('ordonnance/_delete_form.html.twig') }}
{% endblock %}